export const ADMIN_ROLE_NAME = 'Admin';

export const ADMIN_PERMISSIONS = {
  organization: [
    'create',
    'view',
    'edit',
    'copy',
    'delete',
    'bulk',
    'upload',
    'download',
  ],
  project: [
    'create',
    'view',
    'edit',
    'copy',
    'delete',
    'bulk',
    'upload',
    'download',
  ],
  team: [
    'create',
    'view',
    'edit',
    'copy',
    'delete',
    'bulk',
    'upload',
    'download',
  ],
  group: [
    'create',
    'view',
    'edit',
    'copy',
    'delete',
    'bulk',
    'upload',
    'download',
  ],
  ip_address: [
    'create',
    'view',
    'edit',
    'copy',
    'delete',
    'bulk',
    'upload',
    'download',
  ],
  task: [
    'create',
    'view',
    'edit',
    'copy',
    'delete',
    'bulk',
    'upload',
    'download',
  ],
  task_advance: ['self', 'others', 'groups'],
  settings: ['theme'],
  others: ['calendar', 'ai', 'fileManager', 'mail', 'chat'],
} as const;
